//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Our.Umbraco.uSocial.Web.UI.Umbraco.Plugins.uSocial {


	public partial class FacebookOAuthCallback
    {
    }
}
